export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const USER_LIST_SCREEN = 'USER_LIST_SCREEN';
export const USER_DETAILS_SCREEN = 'USER_DETAILS_SCREEN';
export const USER_PROFILE_SCREEN = 'USER_PROFILE_SCREEN';
export const USER_REPOS_SCREEN = 'USER_REPOS_SCREEN';
export const USER_FOLLOWERS_SCREEN = 'USER_FOLLOWERS_SCREEN';
